Update solr server notes in README
cul/ldpd-findingaids-asi pull request #123
Opened 2024-12-23 19:24 UTC by elohanlon

2024-12-23 19:26 UTC, elohanlon commented
@barmintor @bonniegee I've only been using the Docker solr setup recently, so I updated the README to add more details about how to use Docker solr.  I retained the alternative solr instructions in this readme, but broke them out into a separate bullet.  Do either of you still use `bundle exec rake acfa:server`, or should we consider removing it from the README if it's no longer a recommended way to do development?

2025-01-03 16:34 UTC, bonniegee requested changes
I really like breaking this out into sections! I left one comment with a possible change.

2025-01-03 16:34 UTC, bonniegee commented on README.md
> +   1. **Option 1:** Run `docker compose up` to start the solr server and then run `bundle exec rake acfa:seed` to seed the solr server with sample data.  When you are done with development and wish t
I think we can remove instructions for how to shut down the docker container since it's one way (of multiple options) to do so, and is not specific to the app. But I am nitpicking because I do this differently :)

2025-01-06 20:06 UTC, elohanlon commented on README.md
> +   1. **Option 1:** Run `docker compose up` to start the solr server and then run `bundle exec rake acfa:seed` to seed the solr server with sample data.  When you are done with development and wish t
Good call!  I just pushed a commit that removes that shutdown note.

Since you and I both use Docker, is the `bundle exec rake acfa:server` solr setup something you want to continue to support?

2025-01-09 22:15 UTC, merged

2025-01-09 22:15 UTC, barmintor commented
Merging since the requested change was made; we can refine further as needed.