add arclight solr8 configs for development and testing (ACFA-405)
cul/ldpd-findingaids-asi pull request #46
Opened 2023-07-24 21:07 UTC by barmintor

2023-07-24 21:11 UTC, barmintor commented
@fcd1 I'm working on getting Solr 8 on the dev host, but this should let a developer run a local solr for testing. We can't add indexing of the fixture data until we add the `arclight` gem - that's in a separate ticket.

2023-07-24 21:19 UTC, bonniegee requested changes
I was able to get solr running using docker compose. Is it possible to add these instructions (and any other quick start info for a developer) to the readme?

2023-07-24 21:29 UTC, barmintor commented
@bonniegee great point - I added some notes to start, but we will want to revisit them as this feature branch evolves.

2023-07-25 13:25 UTC, bonniegee approved these changes

2023-07-25 13:28 UTC, merged