Add API endpoints for indexing, deleting collections
cul/ldpd-findingaids-asi pull request #81
Opened 2024-04-17 18:15 UTC by bonniegee

Fixes ACFA-492 + includes API endpoint that was already merged into v1.x.

@elohanlon and @nwalker2398 -- would appreciate either of your review as we word on the first part of this together. In particular, I'm not sure if I should have a set up/teardown method on the test for the deletion endpoint.

2024-05-22 19:50 UTC, elohanlon commented on app/controllers/api/v1/index_controller.rb
> +          Rails.logger.debug "no files indexed at #{glob_pattern}"
```suggestion
          Rails.logger.debug "no files indexed for bibids: #{bibids.join(', ')}"
```

2024-05-22 19:55 UTC, elohanlon commented on app/jobs/delete_ead_job.rb
> +    puts solr_response.inspect
```suggestion
```
Okay to remove this puts line?

2024-05-22 19:56 UTC, elohanlon commented on app/jobs/delete_ead_job.rb
> +    `curl #{solr_url}suggest?suggest.build=true`
```suggestion
    Acfa::Index.build_suggester(solr_url)
```

2024-05-22 20:58 UTC, elohanlon requested changes
Looks good!  I only had a few small suggestions.

2024-05-23 14:47 UTC, bonniegee commented on app/jobs/delete_ead_job.rb
> +    `curl #{solr_url}suggest?suggest.build=true`
@elohanlon I had changed this back to using curl command because I couldn't get the other approach to work; see ACFA-491.

2024-05-23 19:36 UTC, elohanlon commented on app/jobs/delete_ead_job.rb
> +    `curl #{solr_url}suggest?suggest.build=true`
Bonnie and I pushed a commit with an update and an additional test to address this.

2024-05-23 19:37 UTC, merged